apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: This a Kubernetes namespace 
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
