---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.name }}
  annotations:
    backstage.io/kubernetes-id: ${{ parameters.cluster }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
