---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: k8s
spec:
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-namespace
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
